### ISSUE TITLE
Django does not correctly detect HTTPS

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-websites/www.ubuntu.com#1031]
Django does not detect HTTPS, likely because it is behind a proxy.
This causes generated URLs and redirects to point to HTTP, which is then redirected back to HTTPS.

Django has a setting called `SECURE_PROXY_SSL_HEADER` to account for this, along with some safety warnings: https://docs.djangoproject.com/en/1.10/ref/settings/#secure-proxy-ssl-header

We should investigate how to set this correctly, or an alternative option to correctly set the SSL flag.

**Comment by nottrobin** [comment]
Yes, the problem here is that in production there are two levels between the SSL negotiation and the Django app:

Apache (SSL termination) -> haproxy -> Django

Apache *should* be setting a request header to signify that it was decoded from a secure connection, and I believe HAProxy should just transparently pass it through to Django.

So the next step is to collaborate with the infrastructure team to inspect the request headers that the production Django app are seeing.

**Comment by WillMoggridge** [comment]
I have created a PR to detect the header. This header needs to be added to our mojo config as a step 2.

The header is set on canonical and assets manager, and is read by assets manager correctly.

**Comment by nottrobin** [comment]
@WillMoggridge out of curiosity, why do we need this? What part of this app uses it? Is it for a callback of some kind?

**Comment by WillMoggridge** [comment]
It was originally created for a redirect forwarding from https to http, which then fires back to https.
This has been implemented across a variety of our sites now and I believe is implemented on ubuntu.com.
