### ISSUE TITLE
invalid certificate

### ISSUE THREAD

**Issue by harridu** [canonical-websites/www.ubuntu.com#1150]
## Summary

The certificate for https://www.ubuntulinux.org/cloud/kubernetes doesn't match.

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
harridu

we don't normally point people to this domain; however, it shouldn't error, so I have filed a ticket with our IS team.

thanks!

Peter

**Comment by pmahnke** [comment]
https://rt.admin.canonical.com/Ticket/Display.html?id=97760 relates.

**Comment by pmahnke** [comment]
IS is still working on this ... related [internal RT][(https://portal.admin.canonical.com/97760)

**Comment by pmahnke** [comment]
ok, this work has been completed

* http://www.ubuntulinux.org/cloud/kubernetes will redirect to https://www.ubuntu.com/containers/kubernetes
* https://www.ubuntulinux.org/* will error properly - since we don't have certificates for ubuntu.net or ubuntulinux.org, we can't make SSL work, but we can (and have) shut the port down so that anyone trying to access them over HTTPS will just get a connection error, rather than the certificate error you reported.

thanks!
