### ISSUE TITLE
add a /server/provisioning redirect please

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#1435]
If the url is not going to reflect the IA (for some reason?), then I think we should at least add a /server/provisioning redirect please. 
See comment in copy doc: https://docs.google.com/document/d/1IrlcBMrX_TDrRC8U1_QSbEOEJ55pGY7nnCd-nfZfiXM/edit

---
*Reported from: https://www.ubuntu.com/server/maas*

**Comment by pmahnke** [comment]
@frankiegranato

can we talk about this?  a couple things:

1. only one person has ever tried the link /server/provisioning... it was on the 14 March, it was probably you
2. I don't like the fact that the menu and the h1 are so different, perhaps we should look at that instead?
3. the /download/server/provisioning is even  worse because at that point, you should be aware you are installing MAAS

**Comment by deadlight** [comment]
I think that this will be swept up in the upcoming IA and URL restructuring
