### ISSUE TITLE
/legal/terms-and-policies/privacy-policy sidebar shows up half way through content in S screen

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1774]
How can we make this appear at the bottom?

**Comment by barrymcgee** [comment]
This is consistent with production - the reason for this is because both of those columns are contained within a row.  

The sidebar can't appear at the bottom because the row containing the table further down the page required 12 columns, therefore the usual method of placing all content in an `col-8` and the sidebar in a `col-4` cannot be implemented.

**Comment by yaili** [comment]
OK, I'll remove the vanilla migration label then.

**Comment by pmahnke** [comment]
There is no obvious fix for this, so closing.
