### ISSUE TITLE
Please add a hover-state to the 'platform' strip on homepage

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#1956]
I would suggest a colour change to the icons on hover. Lets consult with Lil or Joana as to colour choice. https://www.ubuntu.com/

---
*Reported from: https://www.ubuntu.com/*

**Comment by pmahnke** [comment]
@yaili or @joanasa89 ?

**Comment by joanasa89** [comment]
Could be orange. @yaili do you have any other suggestion?

**Comment by yaili** [comment]
Sounds good. Could we just do a demo first to make sure it's not too jarring?

**Comment by Caleb-Ellis** [comment]
For the demo I've just duplicated the SVG icons and changed the colour to orange, so it's serving an entirely different image on hover (which is why there's a slight delay on the first hover). I haven't figured out a way to change the colour of SVGs in CSS but I imagine it would be a million times better.

**Comment by anthonydillon** [comment]
@Caleb-Ellis you would have to put the SVG inline.

For example:
https://codepen.io/anthonydillon/pen/dVWEyJ
