### ISSUE TITLE
Secondary navigation looks broken on the thank you page

### ISSUE THREAD

**Issue by carlaberkers** [canonical-websites/www.ubuntu.com#2392]
This is after filling in a contact form:
![screen shot 2017-11-03 at 13 38 09](https://user-images.githubusercontent.com/7945048/32389514-c4490cf6-c0c2-11e7-9bc3-77b798d49a09.png)

Using Chrome 61
on OSX 10.12.6

---
*Reported from: https://www.ubuntu.com/server/thank-you*

**Comment by anthonydillon** [comment]
@carlaberkers thank you for taking the time to file this issue. We will get a fix it as soon as possible.

**Comment by deadlight** [comment]
I think that it was caused by this commit: https://github.com/canonical-websites/www.ubuntu.com/commit/ee7b90adebda8341d432974b1c0a9050bb328647

It wasn't present on a slightly older revision of the site.

There's another example of the issue on the [legal pages](https://www.ubuntu.com/legal/ubuntu-advantage)
