### ISSUE TITLE
Option to use markdown?

### ISSUE THREAD

**Issue by BryanQuigley** [canonical-websites/www.ubuntu.com#2395]
## Summary

We'd love the option to have pages like https://github.com/canonical-websites/www.ubuntu.com/blob/master/templates/legal/ubuntu-advantage/service-description.html
generated from markdown.

This page is very useful to have an easy to parse diff for (for support/legal reasons).  Markdown gives us much nicer diffs than html. 

I see two ways to do it:
* If the tooling already supports markdown we use that (or we wait for it, if it's coming)
* Otherwise we could have a md file in the tree with instructions (or a script) on how to turn it into a HTML file.

I have a proof of concept markdown that gets us most of the way there.  (Need to figure out Table of Contents and the {% extends part.)

**Comment by pmahnke** [comment]
@BryanQuigley if you are looking for a diff, we do have this as a google doc with version history.

Also, we are likely to pursue your second option of pre-processing at some point.  But do you have an immediate need to know the slight changes in this doc?

**Comment by BryanQuigley** [comment]
We're using the HTML diff changes for now.  If the second option is likely to come (at some point), that's perfect!

**Comment by nottrobin** [comment]
I've done something a bit like this here: https://github.com/nottrobin/www.ubuntu.com/blob/netlify-legal/webapp/views.py#L46

**Comment by nottrobin** [comment]
The site's template finder now supports parsing Markdown, since https://github.com/canonical-websites/www.ubuntu.com/pull/4390.

The only current example of this feature being used is for [the Kubernetes docs](https://github.com/canonical-websites/www.ubuntu.com/tree/master/templates/kubernetes/docs), but we could convert other pages to Markdown.

I'm closing this as resolved - if you think there's value in converting specific pages, please file a separate issues to continue that discussion.
