### ISSUE TITLE
The search on this site is also searching jujucharms.com

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2858]
When [searching for `irc`](https://www.ubuntu.com/search?q=irc) the top results are search results from jujucharms.com. This doesn't seem helpful or contextual.

**Comment by nottrobin** [comment]
@anthonydillon this is because we have one search server that indexes all our sites, and then we filter this by domain when needed. The www.ubuntu.com search deliberately returns results from all of our because we felt this was a reasonable experience - all Canonical products are tangentially related to www.ubuntu.com. Also, a lot of these sites don't have a search of their own.

I agree it might be incongruous for the top result of a search on www.ubuntu.com to come from jujucharms.com, especially when jujucharms.com has a search of its own, but I would still suggest that it still makes sense for www.ubuntu.com search to return results for docs.ubuntu.com, insights.ubuntu.com, tutorials.ubuntu.com and even maas.io, while maas.io doesn't have its own search page.

Ultimately I'd like to solve this confusion by moving the user experience closer to the technical reality by having one domain for this unified search -  probably search.ubuntu.com or search.canonical.com. The site search box on all sites would then send you to e.g. https://search.canonical.com/q=MY_SEARCH&domain=www.ubuntu.com, and that site would then have the appropriate branding and UI to make it clear that you're in a central Canonical search location, filtered by a specific domain, with the ability to add or remove other domains if you want to.

I'm not quite sure how to handle searches that aren't website searches - e.g. searching for charms or snaps. It could be that we leave those searches on snapcraft.io and jujucharms.com respectively, or we could roll it into search.canonical.com, such that you could add or remove snaps or charms from your search filters.

However, this solution will take a fair time to discuss and define, and a little while to implement. In the meantime, you could simply come up  with a list of sites you think *should* be searchable from www.ubuntu.com, and add that filter into the search form, such that you end up at results URLs like the following:

https://www.ubuntu.com/search?q=cloud&domain=www.ubuntu.com&domain=docs.ubuntu.com&domain=tutorials.ubuntu.com&maas.io

Or with only slightly more effort, we could add these filters into the search view to avoid the long URLs, but provide less transparency.

**Comment by matthewpaulthomas** [comment]
Fixing #3142 would coincidentally eliminate the example given here.

I think the question “Will someone expect a site search from page A to return page B?” is equivalent to “Do they perceive A and B to be on the same site?”

(“Site search” is a loaded term, but I mean, “a search field in site navigation, not labelled as having a different scope”. So, not charms or snaps.)

We may have different predictions of what users will perceive as “the same site”. Users may vary too.

Regardless, though, if someone perceives A and B as being on _different_ sites, then I don’t see how putting the search results page on its own domain would make B seem any more helpful or contextual than it was before. If they had entered the search _on_ that separate domain, then maybe … but they didn’t.

**Comment by nottrobin** [comment]
@matthewpaulthomas you're right that the question of which domains should be returned when searching from www.ubuntu.com needs to be decided either way. A central search site doesn't itself that question.

However part of the reason that www.ubuntu.com returns results from so many domains right now is that we have a large number of sites where there is no other way to search them, and their content could easily be of interest to users of www.ubuntu.com. Adding search pages to every one of these sites is infeasible.

If we had a centralised search service which would make it very easy to search any domain quite simply, it wouldn't matter so much if www.ubuntu.com only returned results from www.ubuntu.com, if you could then obviously choose to tweak your filters to add in other Ubuntu domains. We could both not surprise the user with results from another domain, whilst also clearly offering the option to expand their search to those domains.

**Comment by nottrobin** [comment]
Search no longer returns results from jujucharms.com, since we released #3791.
