### ISSUE TITLE
make www.ubuntu.com redirect to ubuntu.com

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#3295]
ubuntu.com is the primary url for the site.

- update redirects where possible
- requires an RT

**Comment by shivjoshi1996** [comment]
@nottrobin We're under the assumption that you said this wasn't technically possible due to security concerns, could you please describe those concrerns below? Thanks

**Comment by nottrobin** [comment]
I'm not sure this should be closed yet. Although I think there are strong arguments against removing the www from www.ubuntu.com, we should still consider it "under discussion". I think closing it is @pmahnke's call. 

# Summary

There's some risk, but not quite as much as I thought, to moving www.ubuntu.com to ubuntu.com.

Overall, given that I was a bit mistaken about how cookies work, I don't think I can entirely recommend either that we *don't* or *do* remove the www - it depends how much we as a company care about it.

But we could do some more investigation into existing subdomains and how they use cookies to help to inform us.

I know this comment is long but at least @pmahnke should read it all.

# Usability perspective

## It's nicer

Personally, I think websites look much cleaner without the www. The www is a cryptic acronym meaning "world-wide-web", which is basically useless information when a user is trying to type a website into a browser - I think we can safely say it's assumed that it's on the world-wide-web (if they know what it means). Historically, it exists because a domain might provide many services - ftp.example.com, ssh.example.com, api.example.com & www.example.com for the website - but I think what most people want most of the time is so obviously the website, so that's a sensible default to host on the main domain. And it's much nicer & quicker to read & write "example.com" than "www.example.com". So I'd always advocate for removing the www unless there are strong reasons not to - which there may be.

## Negative SEO impact

This isn't huge, but worth mentioning.

Google et al. will consider ubuntu.com to be a separate domain to www.ubuntu.com, so any PageRank or similar score associated with pages on www.ubuntu.com will not *automatically* apply to ubuntu.com. However, as long as there are 301s from one to the other, ranking should be transferred.

Nonetheless, we can probably expect a slight drop in ranking for some search terms for a short period by switching domain.

https://moz.com/community/q/switching-site-from-non-www-to-www

# Technical risks

Although the work of switching from one domain to the other is trivial, there are 2 technical risks to using the apex domain:

## DNS

Unlike with subdomains, you can't use a "CNAME" DNS record on the apex domain, you can only use an "A" record to directly point the apex at one or several IP addresses.

This directly impacts us because our Kubernetes ingress uses round-robin DNS to point to (currently) 6 different nodes:

``` bash
$ host prod-comms.kubernetes-ingress.canonical.com
prod-comms.kubernetes-ingress.canonical.com has address 162.213.33.205
prod-comms.kubernetes-ingress.canonical.com has address 162.213.33.141
prod-comms.kubernetes-ingress.canonical.com has address 162.213.33.20
prod-comms.kubernetes-ingress.canonical.com has address 162.213.33.233
prod-comms.kubernetes-ingress.canonical.com has address 162.213.33.142
prod-comms.kubernetes-ingress.canonical.com has address 162.213.33.207
```

docs.ubuntu.com, for example, points to prod-comms.kubernetes-ingress.canonical.com with a CNAME record, meaning it automatically inherits all 6 of those servers. But an apex domain, like snapcraft.io, has to independently keep that list updated, and can fail to do so - when I looked just now it had got out of date leading to https://portal.admin.canonical.com/C112864/.

However, I think this is not a good enough argument not to use the apex domain, as we can simply put processes in place to make sure we keep the DNS up to date properly.

## Cookies

This is potentially more of an issue than the DNS issue. My initial objection here might have been wrong - I [read that](https://serverfault.com/a/145784/92291) all cookies set on an apex domain (example.com) are accessible by subdomains (sub.example.com). This is *not* correct. What is correct:

- By default, all cookies are only visible on the *exact* current domain - cookies on example.com are only visible from example.com, cookies on sub.example.com are only visible on sub.example.com
- Code on the apex domain (example.com) *can choose* to set a cookie so it is readable on subdomains (sub.example.com) by setting the "domain" to ".example.com"
  - E.g., many cookies on snapcraft.io (e.g. `_ga`, `_gid` etc.) are also visible to forum.snapcraft.io
- Code on subdomains (sub.example.com) *can choose* to set a cookie so it is readable from the apex domain

There are both performance and security implications from this:

- Many JavaScript libraries that you allow to run on your apex domain, like Google Analytics, may set cookies that are visible on subdomains, and vice-versa
  - This isn't a security concern directly - it enables tracking, but presumably if you've added Google Analytics it's cos you want that tracking
  - This could be a performance concern - those cookies are added to the headers in each HTTP handshake, bloating all communication
- Any subdomain that isn't controlled by us (e.g. rogue.ubuntu.com) could set cookies that would then appear on ubuntu.com. 
  - Depending on how we use cookies on ubuntu.com, this *could* be a security concern. It's difficult to imagine an example, but if we were actually using information in Users' cookies to determine what a user sees on ubuntu.com, there could be a sort-of XSS attack. But this would be a stupid thing to do for many reasons.
  - Even if it wasn't a security concern, it could at least be a performance concern - peoples' communication to ubuntu.com could become quite bloated.
- If we weren't paying attention, we could accidentally set a sensitive cookie, e.g. one containing authentication information, to be accessible from subdomains including e.g. rogue.ubuntu.com. This would be a *major* security issue. But hopefully it's not something we would accidentally do.

Overall, these issues are probably tolerable depending on how much we really want to remove the www - especially since ubuntu.com currently doesn't have sessions or authentication. There are important questions to answer though:

- How many subdomains of ubuntu.com are setting cookies that would be added to ubuntu.com payloads?
- How many subdomains of ubuntu.com lead to applications that are not under Canonical's control?

**Comment by nottrobin** [comment]
Okay this is embarrassing. Thinking about it some more, I've realised that the cookie argument is entirely irrelevant: Since any apex domain or subdomain can set cookies with `domain=.ubuntu.com`, which will then be visible from any other apex domain or subdomain, there is no difference between having our main site on www.ubuntu.com or ubuntu.com.

Therefore I need to change my recommendation to saying that in fact moving www.ubuntu.com to ubuntu.com is entirely doable. There are no more downsides than there are for any other apex domains - maas.io, snapcraft.io, cloud-init.io, netplan.io, etc.

**Comment by kasiag** [comment]
@nottrobin can you estimate this work please?

**Comment by nottrobin** [comment]
Estimated in, and discussion moved to, https://github.com/ubuntudesign/web-squad/issues/744
