### ISSUE TITLE
Replace the app-store screenshot  

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3387]
We need to create a app-store screen shot with a more iot-centric selection of apps showing under 'Featured' - at Thibaut's request. Thibaut will give us a list of the appropriate apps.  

---
*Reported from: https://www.ubuntu.com/internet-of-things*

**Comment by carlaberkers** [comment]
here is a doc with IoT snaps that should be included in the mock up screenshot:
https://docs.google.com/document/d/1-8FX3z_-kLbYFkuNWxUTM98qYW576M9trN1BmRyHvrc/edit

**Comment by frankiegranato** [comment]
We've decided to wait until the snapping team has produced the store category pages

**Comment by shivjoshi1996** [comment]
After talking in Montreal we have decided to create a mock-up of a branded store, to replace this image

**Comment by Greggless** [comment]
Hey Shiv, Ana and I were talking about this. Do you have any notes from the meeting?

Is Ana to create a 'White-label' version of the snap store, with a bunch of IoT centric snaps. Much like what the screenshot is showing now, just without the 'featured snaps' and Snapcraft branded header?

**Comment by anasereijo** [comment]
Montreal Sprint notes – July 2018:
> Screenshot of the global store should come down, and replace with a mock-up of a branded store. We can also show snaps that are iot centric.

use this link as reference for branded store: https://limenet.staging.snapcraft.io/

**Comment by anasereijo** [comment]
Hi @Greggless I would like to have your opinion on this :)

I created a mockup for a branded store and used the snaps that were on the copydoc. As we discussed would be ideal to have 6 snaps in a row, right? If so, can you please suggest another one?
Because we don't have many IoT snaps the screenshot it will look very short, but I guess it's all we have for now. Any thoughts/suggestions?

It will look like this on ubuntu.com:

![Screen Shot 2018-07-20 at 14.20.16.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/22261436-61e1-4e65-aa85-6f424703b23a)

**Comment by Greggless** [comment]
- A user will likely need to be signed in to access the store, so maybe use 'Jane foo 🔽' instead of 'sign in/register'
- These snaps aren't _by_ Acme_corp, they're just in their store. Maybe we can leave that `H3` out of it 
- I think we could use some more obvious IoT focussed snaps, things with words like embedded, core, IoT, server in the title, or published by a recognised name, or have a super-cool-IoT logo
  - [Try this](https://snapcraft.io/kura-nn) instead of Nymea
  - And add [this](https://snapcraft.io/homebridge) in there, too
- Do we want to add another row of snaps at all? We can crop it so that we only show the top half of the icons to show that there could be more in a real brand store?

**Comment by anasereijo** [comment]
Thanks, @Greggless for your help and suggestions.

See below the updated screenshot :) it's looking much better, I think.


![screen shot 2018-07-20 at 14 20 16](https://user-images.githubusercontent.com/36884067/43007615-bfae4e60-8c30-11e8-8204-20904afd4ba3.jpg)

**Comment by carlaberkers** [comment]
This looks much better, thank you Ana!

**Comment by anasereijo** [comment]
note: Thibaut has seen it and he is happy.

**Comment by kasiag** [comment]
@frankiegranato has seen this and she's happy
