### ISSUE TITLE
Resources do not appear on the resource page

### ISSUE THREAD

**Issue by campbieil** [canonical-websites/www.ubuntu.com#3801]
![screen shot 2018-07-26 at 09 38 36](https://user-images.githubusercontent.com/230348/43251430-ce1ccea0-90b7-11e8-9f50-462592b30bec.png)
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Resources do not appear on the resource page

## Process

visit https://www.ubuntu.com/resources, on a random basis the feed from blog does not appear

## Current and expected result

Expecting to see the list of resources, but this does not seem to always show

## Screenshot

See screenshot

**Comment by nottrobin** [comment]
Thanks for filing this.

Normally a page refresh appears to fix it. This is because it's due to a timeout when the cache is empty, but the cache then gets populated, and the next time the page is requested, the cached copy should be there.

The initial timeout should be fixed by https://github.com/canonical-websites/www.ubuntu.com/pull/3856 which will hopefully go live today.
