### ISSUE TITLE
We invite readers to report bugs when “The live news feed failed to load”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#3993]
1\. Go to [“Community support”](https://www.ubuntu.com/support/community-support).
2\. Scroll to the middle.

What you see: “Error:The live news feed failed to load. Please report this bug and our team will fix the problem as soon as possible.”

![3993-news-feed](https://user-images.githubusercontent.com/19801137/44972944-d3c6cb80-af52-11e8-8e29-0a7e0d9814d2.png)

What you should see: No such error.

**Comment by matthewpaulthomas** [comment]
Turns out this is just because blog.ubuntu.com is down. The same problem occurs on [ubuntu.com/resources](https://www.ubuntu.com/resources).

I still think this is a bug, though — that blog.ubuntu.com is down is not something we should be inviting readers to report a bug about. If we don’t have an automatic way of detecting that, we should; and if we do, then asking for bug reports as well is wasting both their time and ours.

So the message should say something like “Sorry, the news feed isn’t available at the moment. We’ll fix it as soon as possible.”

**Comment by anasereijo** [comment]
@nottrobin is this something you can help us with?

**Comment by nottrobin** [comment]
> @matthewpaulthomas: I still think this is a bug, though — that blog.ubuntu.com is down is not something we should be inviting readers to report a bug about. If we don’t have an automatic way of detecting that, we should; and if we do, then asking for bug reports as well is wasting both their time and ours.

We do have alerts to tell us if blog.ubuntu.com is actually down, and we respond to those alerts very quickly, but that very rarely happens. Users see this error when blog.ubuntu.com is working fine, but e.g. the feed behind the scenes in ubuntu.com times out, or sometimes because it's unable to process content in one of those articles, or something.

We don't currently have particularly good automated ways to detect every time that feed might fail for a user (Sentry could provide this, but it's currently just too noisy for us to actually respond to its alerts with any urgency), and so in the absence of such automated alerts we ask users to report bugs so that we aren't totally oblivious to these problems.

However, errors with `/resources` (and probably `/support/community-support` as well) are all too common, and we really need to try to look into ways to fix them quite urgently. Given that at the moment we're aware that there are issues, and so right now we certainly risk getting many issues from users about problems we're already aware of. But on the other hand the constant stream of issues will actually help keep reminding us that it needs fixing.

So @matthewpaulthomas I would say that this message is performing a useful function for us, certainly for the time being. We will continue to try to improve both the stability of those endpoints and also work on better automated alerting, so maybe we can reduce reliance on asking website users to file issues in the future, but not yet.
