### ISSUE TITLE
Update user report page to match visual design 

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4094]
https://docs.google.com/document/d/153OkfZHM_eTfAoUZF3f38VMtiFzaa2txB9B2lvs8xXA/edit

**Comment by anasereijo** [comment]
@inuwa can you please estimate this task? FYI @anthonydillon @shivjoshi1996

**Comment by anasereijo** [comment]
Hi @inuwa,

this is finally ready to be built :)

I made a sketch with all the settings (font sizes, graphs settings, etc) because I thought it may be easier for you (see attached to this comment). Please do let me know if you need help :)

Here are a couple of links and things you also need to know:
- orange colour: #E95420
- aubergine colour: #772953
- grey used (only) on graphs: #E5E5E5
- hero section background colour: #F7F7F7
- hero section left side suru fold: https://assets.ubuntu.com/v1/8f96f63c-suru-left-side.svg
- hero section right side suru fold: https://assets.ubuntu.com/v1/95d86dd2-suru-right-side.svg
- hero section h1 should be thin

you can see a final version without my comments here: https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/3951

![FINAL-VERSION_settings.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/b2f9d8d9-a7e5-44f3-b183-32a03902c837)
