### ISSUE TITLE
Refreshing blog.ubuntu.com cycles through revisions of blogpost, instead of displaying the latest

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-websites/www.ubuntu.com#4855]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Refreshing https://blog.ubuntu.com/, I can see the featured image and excerpt of my blog post (the one in the middle) alternate between the last few revisions. See this (unlisted) video:
https://youtu.be/Fo6fW4yOPzg

## Process

Change featurted image / excerpt on a newly published blog post a few times.
Observe issue.

**Comment by anasereijo** [comment]
@lyubomir-popov I tested and that happens on my machine too. 

It's also not showing the card footer tag (see below)

![Ubuntu blog](https://user-images.githubusercontent.com/36884067/54699766-93631f80-4b29-11e9-8dbe-22b99f53e9a1.png)

**Comment by anasereijo** [comment]
@pmahnke is this something you can fix or is it a backend task?

**Comment by lyubomir-popov** [comment]
@anasereijo Yes, this seems to be an additional issue - updating the article seems to delete quick edit changes like setting categories etc. But haven't been able to reliably reproduce this.

**Comment by lyubomir-popov** [comment]
Also as can be seen on a browser I don't use - safari - it takes about 20sec to refresh the page.

**Comment by nottrobin** [comment]
So this will be because the server-side application API requests to Wordpress are [cached for an hour](https://github.com/canonical-websites/blog.ubuntu.com/blob/master/feeds.py#L37) - This is currently needed because the API is very slow.

And in production we run [5 replicas](https://github.com/canonical-webteam/deployment-configs/blob/master/services/blog-ubuntu-com.yaml#L23) of the application, and the caching is at the application level, and so when you refresh you are randomly sent a response from 1 of those 5 replicas, whose caches probably refreshed at slightly different times.

So, in the current situation, you should see eventual consistency on displaying the latest version of the blog data, but it could take up to an hour.

We are working with IS to address this in two different ways - one is [better leveraging the Squid cache in front of blog.ubuntu.com](https://portal.admin.canonical.com/C117166/) so that we can reduce the cache time for API requests, and another is to [use a centralised caching service](https://portal.admin.canonical.com/C116787) rather than caching at the application level, which would remove the inconsistencies between replicas.

Since these other streams are already in progress, but unfortunately can't be fixed imminently, I'm going to close this for now. I hope that's okay.

**Comment by lyubomir-popov** [comment]
Thanks for the detailed explanation @nottrobin!
