### ISSUE TITLE
Try to defer or asynchronously load blocking resources

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#656]
We have a number of javascript assets blocking the page render. Lets try and remove where possible and if required try to defer or async to load.

Here is a list of assets:
- https://assets.ubuntu.com/v1/b0601acd-modernizr.2.7.1.js
- https://assets.ubuntu.com/v1/2c8fd8c9-Imager.js
- https://assets.ubuntu.com/v1/5d7e5bbf-jquery-2.2.0.min.js
- http://www.google-analytics.com/…api.js?experiment=IbIACoOrTnG8eSnRY64nWQ
- https://assets.ubuntu.com/v1/c954db4a-jfeed_prm.js

**Comment by pmahnke** [comment]
@anthonydillon and @nottrobin is this part of your current YUI conversion work?

**Comment by nottrobin** [comment]
@pmahnke I don't suppose this is directly related to removing YUI, so not super urgent. It's more related to generally tidying up JS.

**Comment by anthonydillon** [comment]
Not connected directly but something we should look at while we are there.

**Comment by pmahnke** [comment]
@anthonydillon and @nottrobin how is this looking post YUI?

**Comment by anthonydillon** [comment]
I believe we can not async all javascript now that they are depending on a
framework.

**Comment by nottrobin** [comment]
## Loading dependencies

No matter whether we have a framework or not, there's always going to be some bits of JavaScript depending on others. So we always have to make sure that for any JavaScript, anything it depends on is loaded first. So most stuff will need `Modernizr` to have loaded, most stuff will need `polyfills.js`, and a few things will need `jQuery`.

I suppose there are 3 main approaches we could go for here:

1. Load these modules above any JavaScript, as we're doing now. This will lead to maximum page blocking. Although we could move these blocking calls lower down the page.
2. Use something like [require.js](http://requirejs.org/) to asynchronously load in the dependencies when they're needed (I think @WillMoggridge would like this). This is probably the best way to avoid blocking the page, but it will delay JavaScript loading the longest while multiple HTTP requests are made to pull in all dependencies.
3. Bundle all JavaScript into a single file. This has the downside that a page might be downloading much more JavaScript than it needs.

## How far down the page?

Even if we went for the most blocking option above (option 1), we could still choose to put all the JavaScript at the bottom of the page. This would mean that even though the page wouldn't *finish* loading until the JavaScript had been loaded, all the actual content would load first.

The downside to this is it means we don't have the option to run any JavaScript before the page has almost finished loading. In some situations this delay could lead to a pretty poor user experience - e.g. with elements being hidden or shown 3 seconds after they load.

## The ideal solution requires HTTP/2

There is a holy grail here. With HTTP/2's [server push](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/) it would be possible to send all the needed JavaScript files along with the initial response that sends the HTML file, completely removing the overhead of subsequent HTTP requests.

We could then happily use [require.js](http://requirejs.org/), because all module loads would be instant, as the files would already be locally available.

However, we don't yet have a working implementation of HTTP/2 on any site, so it'll be a while (>6 months?) until we have it on www.ubuntu.com. And even then, setting up the app to successfully push all required resources seamlessly is non-trivial.

**Comment by anthonydillon** [comment]
Ah yes, `Modernizr` and `polyfills.js`.

`Modernizr` cannot be deferred or asynced as it is required to add body
classes before the page is rendered. Otherwise we would have movement of
content as the CSS is triggered. This means we cannot move this further
down the page. I believe we only use the `no-svg` class that is generated.
We could check for just that and pop that check in the head as a inline
snippet? Alternatively, could we begin to use `@supports` instead and
remove `Modernizr` all together?

`polyfills.js` could move to just above the other js files but could not be
asynced as it is needed before other js. I wonder if we couldn't just place
this small js snippet in the footer of each page? In that case we would
need to look at the order in the footers.

Therefore, that leaves us all the rest of the js being async. That would
still be a huge improvement.

**Comment by nottrobin** [comment]
I don't think CSS feature queries should be used for detecting SVG support, as support for them [is *much* worse](http://caniuse.com/#search=feature%20queries) than [support for SVGs](http://caniuse.com/#search=SVG). 

However, if SVG is really the *only* thing we need from Modernizr, I would suggest we get rid of Modernizr. We could either go for [a JavaScript-less solution](https://css-tricks.com/svg-fallbacks/) or find or write our own much smaller snippet of JavaScript to mimic what Modernizr currently does for us, which we could then just include directly in the page to avoid any loading overhead.

`polyfills.js` *can* be loaded async as long as we have a callback mechanism for loading any dependent JavaScript (as YUI used to do). This doesn't mean this is what we want to do. I think the best option *might* be to bundle all JavaScript together at that point, depending on how much extra weight this would mean we're loading across pages that don't need it...

**Comment by nottrobin** [comment]
Actually thinking about it there's no reason why SVG fallbacks have to load in the `<head>`. If they load after the page, the worst you'll get is a flash of missing images in browsers that don't support SVG - this doesn't seem like the worst thing in the world.

The one thing which really needs `<head>` is the HTML5 shim. But this is actually a *really small* snippet of JavaScript, which we could easily place directly in the `<head>` ourselves.

The only other thing is the `no-js` class, but once again, that should be trivial to write ourselves.

**Comment by anthonydillon** [comment]
+1 from me. Lets use the Modernizr function for SVG detection and pop it in
the head.

**Comment by nottrobin** [comment]
We have agreed a way forward.

# Minimal solution

1. Remove Modernizr

2. Place directly in the `<head>`:
    - [HTML5 shiv](https://github.com/aFarkas/html5shiv/blob/master/dist/html5shiv.min.js)
    - The [`no-js` replacement](https://css-tricks.com/snippets/javascript/css-for-when-javascript-is-enabled/):
      
      ``` javascript
      var html = document.documentElement
      html.className = html.className.replace('no-js', 'js')
      ```

3. Place the minified contents of [polyfills.js](https://github.com/ubuntudesign/www.ubuntu.com/blob/master/static/js/polyfills.js) at the bottom of the page, but before any real JavaScript is loaded.

4. Move all other JavaScript to the bottom of the page, below the now inline polyfills.

5. In [core.js](https://github.com/ubuntudesign/www.ubuntu.com/blob/master/static/js/core.js), [use `hasFeature`](https://css-tricks.com/test-support-svg-img/) instead of `Modernizr.svg`:

    ``` javascript
    document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image", "1.1");
    ```

# A better solution

In the slightly longer run, but still fairly soon, we should look into doing one of:

- Bundling all the JavaScript together in one file which we call at the bottom of the page - in this case that file might as well include `polyfills.js` as well. Or:
- Using [RequireJS](http://requirejs.org/) or similar to pull in dependencies asynchronously.

**Comment by anthonydillon** [comment]
:+1: thanks!

**Comment by deadlight** [comment]
@anthonydillon @nottrobin can you guys have a look over this conversation and decide if this is still the preferred solution.
