### ISSUE TITLE
Cloud > Partners: the Premier cloud partner logo is looking elongated [IE9, 10 and 11, Win 7]

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#72]
Its normal size is about the same height of the text block

**Comment by anthonydillon** [comment]
I've looked into this and there is no easy fix. It is due to the svgs themselves having width and height attributes. If these are removed the can control both the height and width.  

There are a few options going forward:
1. Go through each SVG, removing the styling on the svg. Uploading the new version and changing the links across the site.
2. Leave them as they are and except that < IE9 will have odd SVG images. 
3. Write a snippet of JS that triggers in <IE9 which appends all svg images links with `fmt=png`.

@yaili @pmahnke @nottrobin

**Comment by yaili** [comment]
According to the title, the issue is not just on IE9 though, it's 9, 10 and 11.

**Comment by anthonydillon** [comment]
Sorry yes your right. It must effect all <IE10.

**Comment by pmahnke** [comment]
@yaili @pmahnke @nottrobin

It would be nice if the asset server served png's to IE... but I don't think that will just work with all the caching in front.

And I think we will never have full control over all the partner assets, so the javascript solution is the safest.

**Comment by yaili** [comment]
< **and including** IE10

I thought you had already done a JS snippet for this, didn't you? Or was it fixing something else? Opera Mini?

**Comment by anthonydillon** [comment]
That was opera mini. I will extend the functionality to IE too.
